server:
  port: 8081

spring:
  application:
    name: client-service
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/cinema
    password: 'password'
    hikari:
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0