server:
  port: 8081

spring:
  application:
    name: client-service
  datasource:
    username: 'admin'
    url: jdbc:postgresql://localhost:5432/clients
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
